// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvzbpflkjluapzyvfhcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2emJwZmxramx1YXB6eXZmaGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzE2MDEsImV4cCI6MjA2MTUwNzYwMX0.9zpXCbAgNNekKPD9e4U5X_h9WLFkARaKqDv5i5c6CPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);